name: Zip and Commit ExpressJS Folder

on:
  push:
    branches:
      - main

jobs:
  zip-and-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove old ZIP if exists
        run: rm -f apijs.zip

      - name: Zip the ExpressJS Folder
        run: |
          zip -r apijs.zip . -i expressjs

      - name: Commit and Push ZIP File
        run: |
          git config --global user.name "juliocesardemoraes"
          git config --global user.email "jcmcf2012@gmail.com"
          git add apijs.zip
          git commit -m "Auto-update apijs.zip"
          git push origin main
